---
- hosts: all
  become: true
  tasks:
    - name: Install ZSH, acl...
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: true
      vars:
        packages:
          - zsh
          - acl
