---
- hosts: all
  become: true
  tasks:
    - name: Ensure local certs directory exists
      file: state=directory path=/usr/local/share/ca-certificates

    - name: Install myCA cert
      copy: src=MyCA.crt dest=/usr/local/share/ca-certificates/MyCA.crt

    - name: Update cert index
      shell: /usr/sbin/update-ca-certificates
