---
# ansible-galaxy install gantsign.oh-my-zsh
- name: Play for installing oh-my-zsh
  hosts: all
  gather_facts: true
  roles:
    - role: gantsign.oh-my-zsh
      users:
        - username: ubuntu
      oh_my_zsh_theme: refined
      oh_my_zsh_plugins:
        - microk8s
        - git
        - kubectl
        - docker
        - helm
        - command-not-found
        - colorize
        - colored-man-pages
        - themes
        - history

# compdef microk8s.kubectl=kubectl
# compdef mk=kubectl

# alias k=mk
# compdef k=kubectl
