---
- hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Install ZSH, Git...
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: true
      vars:
        packages:
          - zsh
          - git
          - pydf
          - acl
          - python3-pygments
