---
- name: Play for installing microk8s
  hosts: all
  become: true
  tasks:
    - name: Install microk8s for Canonical Kubernetes
      community.general.snap:
        name: microk8s
        classic: true
        channel: 1.25/stable
    - name: Add ubuntu user to microk8s group
      become: true
      ansible.builtin.user:
        name: ubuntu
        groups: microk8s
        append: true
