---
- name: Upgrade packages
  hosts: all
  become: true
  tasks:
    - name: Upgrade all apt packages
      ansible.builtin.apt:
      update_cache: yes
      upgrade: dist
      force_apt_get: yes
      autoclean: yes
      autoremove: yes
