---
- name: Check uptime
  hosts: all
  gather_facts: false
  tasks:
    - name: Get hostname
      ansible.builtin.command: /bin/hostname
      changed_when: false
      register: hostname

    - name: Get uptime
      ansible.builtin.shell: /usr/bin/uptime | grep -ohe 'up .*' | sed 's/,//g' | awk '{ print $2" "$3 }'
      changed_when: false
      register: uptime

    - debug: var={{ item }}
      with_items:
        - hostname.stdout
        - uptime.stdout
